# Generated by Django 4.2.29 on 2026-03-11 14:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='period_type',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('weekly', 'Weekly')], default='monthly', help_text='Cycle for this budget. Currently monthly is fully supported.', max_length=10),
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.CharField(blank=True, help_text='Optional: describe what expenses belong in this category.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='currency',
            field=models.CharField(default='USD', help_text='ISO 4217 currency code, e.g. USD, GBP, KES.', max_length=3),
        ),
        migrations.AlterField(
            model_name='budget',
            name='limit_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
    ]
